version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 127.0.0.1:33306:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p", "test"]
      interval: 20s
      timeout: 10s
      retries: 10  
